# Generated by Django 3.1.4 on 2020-12-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201211_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternode',
            name='pastelID',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
