# Generated by Django 3.1.4 on 2020-12-22 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_masternode_pastelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masternode',
            name='pastelID',
            field=models.CharField(default=123456, max_length=86, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Regticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_pastelid', models.CharField(max_length=86, null=True)),
                ('image_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (-1, 'Error'), (1, 'Placed on blockchain')])),
                ('created', models.DateTimeField()),
                ('masternode_pastelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.masternode', to_field='pastelID')),
            ],
        ),
    ]
