# Generated by Django 3.1.4 on 2020-12-24 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201222_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regticket',
            name='artist_pastelid',
            field=models.CharField(default=django.utils.timezone.now, max_length=86),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regticket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='regticket',
            name='image_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='regticket',
            unique_together={('masternode_pastelid', 'image_hash')},
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=128)),
                ('image_hash', models.CharField(max_length=64)),
                ('indexed', models.BooleanField()),
                ('confirmed', models.BooleanField()),
                ('stored', models.BooleanField()),
                ('mn_pastelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.masternode', to_field='pastelID')),
            ],
            options={
                'unique_together': {('chunk_id', 'mn_pastelid')},
            },
        ),
    ]
