# Generated by Django 3.1.4 on 2020-12-29 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_create_regticket_and_chunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='MNConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('remote_pastelid', models.CharField(max_length=86)),
                ('active', models.BooleanField()),
                ('masternode_pastelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.masternode', to_field='pastelID')),
            ],
            options={
                'unique_together': {('masternode_pastelid', 'remote_pastelid')},
            },
        ),
    ]
