# Generated by Django 3.1.4 on 2020-12-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201223_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mn_pastelid', models.CharField(max_length=86, unique=True)),
                ('chunk_id', models.CharField(max_length=128, unique=True)),
                ('image_hash', models.CharField(max_length=64)),
                ('indexed', models.BooleanField()),
                ('confirmed', models.BooleanField()),
                ('stored', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='regticket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
