# Generated by Django 3.1.4 on 2021-02-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_chunk_chunk_id_256'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternode',
            name='name',
            field=models.CharField(default=123, max_length=35),
            preserve_default=False,
        ),
    ]
