# Generated by Django 3.1.4 on 2021-02-10 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_masternode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternode',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 9, 25, 56, 981172)),
        ),
    ]
