# Generated by Django 3.1.4 on 2020-12-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201223_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chunk',
        ),
    ]
