# Generated by Django 3.1.4 on 2020-12-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201223_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='mn_pastelid',
            field=models.CharField(max_length=86, null=True, unique=True),
        ),
    ]
