# Generated by Django 3.1.4 on 2020-12-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201223_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chunk',
        ),
    ]
