# Generated by Django 3.1.4 on 2020-12-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_chunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='mn_pastelid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.masternode', to_field='pastelID'),
        ),
    ]
