# Generated by Django 3.1.4 on 2020-12-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201224_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='chunk_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='regticket',
            name='image_hash',
            field=models.CharField(max_length=64),
        ),
    ]
